version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: yes

permissions:
  - object: /

hooks:
  BeforeInstall:
    - location: beforeDeploy.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root
