# blue
# blue 컨테이너는 8080으로 포트를 노출해서 실행
version: "3.3"
services:
  dealight-blue:
    container_name: dealight-blue-container
    build:
      context: ./
      dockerfile: dealight.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/volumes/logs:/logs
    environment:
      TZ: "Asia/Seoul"
    restart: always
    networks:
      - dealight-network

networks:
  dealight-network:
    external: true
