# green
# green 컨테이너는 8081으로 포트를 노출해서 실행
version: '3'
services:
  dealight-green:
    container_name: dealight-green-container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      TZ: "Asia/Seoul"
    networks:
      - dealight-network

networks:
  default:
    external:
      name: dealight-network
