spring:
  config:
    import:
      - classpath:application-oauth.yml
      - classpath:application-aws.yml

  datasource:
    url: "jdbc:h2:mem:spring_security;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    database: h2
    open-in-view: false
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true # 필수

#  sql: # depth 주의 jpa와 같은 depth
#    init:
#      data-locations: classpath:data.sql
#      mode: always
#      platform: h2 # 본인 DB 종류

  redis:
    host: localhost
    port: 6379
