server:
  tomcat:
    mbeanregistry:
      enabled: true

management:
  info:
    env:
      enabled: true
    git:
      mode: full

  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      base-path: "/admin/manage"
      exposure:
        include: "*"
        exclude: "env"

info:
  app:
    name: Dealight-BE
    company: Team-PalPal
