spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/dealight # (본인 DB URL)
    username: sa
    password:
  driver-class-name: org.h2.Driver #(본인 DB종류에 맞춰서)
  h2:
    console:
      enabled: true

  jpa: # depth 주의
    open-in-view: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
