server:
  tomcat:
    mbeanregistry:
      enabled: true

management:
  info:
    env:
      enabled: false
    os:
      enabled: false
    git:
      mode: full

  endpoint:
    health:
      show-details: always

  endpoints:
    jmx:
      exposure:
        exclude: "*"

    web:
      base-path: "/admin/manage"
      exposure:
        include: "*"
        exclude: "beans, env, heapdump, shutdown"

info:
  app:
    name: Dealight-BE
    company: Team-PalPal
